Repository PDeXchange/pac, pull requests merged in 2025-07, with the labels that each got.

#382 Added Ut framework and few test cases
  go.mod
  go.sum
  internal/pkg/pac-go-server/client/kubernetes/interface.go
  internal/pkg/pac-go-server/client/kubernetes/mock_kubernetes_client.go
  internal/pkg/pac-go-server/db/interface.go
  internal/pkg/pac-go-server/db/mock_db_client.go
  internal/pkg/pac-go-server/services/backend_test.go
  internal/pkg/pac-go-server/services/catalog_test.go
  internal/pkg/pac-go-server/services/service_test.go
Labels: lgtm, approved, size/XXL

#388 Adding unit tests and interfacing keycloak
  cmd/event-notifier/notifier.go
  internal/pkg/pac-go-server/client/interface.go
  internal/pkg/pac-go-server/client/keycloak.go
  internal/pkg/pac-go-server/client/mock_keycloak.go
  internal/pkg/pac-go-server/router/middleware.go
  internal/pkg/pac-go-server/services/backend_test.go
  internal/pkg/pac-go-server/services/catalog_test.go
  internal/pkg/pac-go-server/services/events.go
  internal/pkg/pac-go-server/services/events_test.go
  internal/pkg/pac-go-server/services/group_test.go
  internal/pkg/pac-go-server/services/key.go
  internal/pkg/pac-go-server/services/key_test.go
  internal/pkg/pac-go-server/services/quota.go
  internal/pkg/pac-go-server/services/quota_test.go
  internal/pkg/pac-go-server/services/request.go
  internal/pkg/pac-go-server/services/request_test.go
  internal/pkg/pac-go-server/services/service.go
  internal/pkg/pac-go-server/services/service_test.go
  internal/pkg/pac-go-server/services/tnc_test.go
  internal/pkg/pac-go-server/services/user.go
  internal/pkg/pac-go-server/services/user_test.go
  internal/pkg/pac-go-server/services/utils.go
  internal/pkg/pac-go-server/utils/utils.go
Labels: lgtm, approved, size/XXL

#394 Set Default Expiration Days For VMs to 5
  apis/app/v1alpha1/catalog_types.go
  controllers/util/util.go
  internal/pkg/pac-go-server/services/catalog.go
  internal/pkg/pac-go-server/utils/utils.go
Labels: lgtm, approved, size/S

#411 Fixed create service issue
  apis/app/v1alpha1/service_types.go
Labels: lgtm, approved, size/XS

#409 Upgrade go to 1.24 to be in sync with upstream
  .github/config/constants.yml
  Dockerfile
  apis/app/v1alpha1/zz_generated.deepcopy.go
  apis/manageiq/v1alpha1/zz_generated.deepcopy.go
  controllers/app/service_controller.go
  go.mod
Labels: lgtm, approved, size/S

#419 Use official PAC name
  CLA.md
  README.md
  cmd/event-notifier/README.md
  internal/pkg/notifier/client/mail/mail.go
  internal/pkg/pac-go-server/models/events.go
Labels: lgtm, approved, size/S

#417 Added swagger api doc for PAC apis
  Dockerfile
  Makefile
  cmd/swagger/main.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  internal/pkg/pac-go-server/router/router.go
  internal/pkg/pac-go-server/services/catalog.go
  internal/pkg/pac-go-server/services/events.go
  internal/pkg/pac-go-server/services/group.go
  internal/pkg/pac-go-server/services/key.go
  internal/pkg/pac-go-server/services/quota.go
  internal/pkg/pac-go-server/services/request.go
  internal/pkg/pac-go-server/services/service.go
  internal/pkg/pac-go-server/services/tnc.go
  internal/pkg/pac-go-server/services/user.go
Labels: lgtm, approved, size/XXL
