Repository PDeXchange/pac, pull requests merged in 2025-09, with the labels that each got.

#455 Workflows for release branches
  .github/workflows/docker-publish.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/unit_tests.yml
Labels: lgtm, approved, size/S

#466 Fix resty: CVE-2023-45286
  go.mod
  go.sum
Labels: lgtm, approved, size/S

#472 Go-Jose: Fix CVE-2025-27144
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#479 Add custom error handling while unmarshalling request body
  internal/pkg/pac-go-server/models/feedback.go
  internal/pkg/pac-go-server/services/catalog.go
  internal/pkg/pac-go-server/services/feedback.go
  internal/pkg/pac-go-server/services/key.go
  internal/pkg/pac-go-server/services/quota.go
  internal/pkg/pac-go-server/services/request.go
  internal/pkg/pac-go-server/services/service.go
  internal/pkg/pac-go-server/utils/errors.go
  internal/pkg/pac-go-server/utils/errors_test.go
  internal/pkg/pac-go-server/utils/utils.go
  internal/pkg/pac-go-server/utils/utils_test.go
Labels: lgtm, approved, size/L

#484 ReadME update
  README.md
Labels: lgtm, approved, size/S

#485 Add FAQ link in service mail expiry message
  internal/pkg/pac-go-server/services/notification.go
Labels: lgtm, approved, size/XS
